### ISSUE TITLE
unrecognized arguments while running sudoku_solver_main

### ISSUE THREAD

**Issue by tariqrahiman** [remi2257/sudoku-solver#2]
Hi Remy,
I am a complete beginner. I configured Anaconda, TensorFlow & CV2. When i run your code - the main file 
sudoku_solver_main.py i get the below error. I know it is a configuration issue. 
Do you have any inputs in this error ? FYI - i saw your post in Reddit

ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\tariq\AppData\Roaming\jupyter\runtime\kernel-901f221c-b69f-454b-b4c8-93b58d2700d8.json

![soduku](https://user-images.githubusercontent.com/913554/90711889-b336cf80-e256-11ea-9034-e9311886721c.png)

**Comment by remi2257** [comment]
You are using "-f" argument which is not valid. Go check your parameters in the kernel.
Run the command `python sudoku_solver_main  -h` to see valid arguments
